---
- name: Get podman imagaes
  ansible.builtin.command:
    cmd: "{{ 'podman images --format {{.Repository}} --no-trunc' }}"
  changed_when: false
  check_mode: false
  register: podman_images

- name: Create/update Navigator configuration
  ansible.builtin.template:
    src: navigator_config.j2
    dest: "{{ ansible_user_dir }}/.ansible-navigator.yml"
    mode: "0644"
    backup: true
  vars:
    ee_image: "{{ podman_images.stdout_lines | select('search', '.*ee-supported.*') | list | first }}"
